name: Payload
on:
  push:
  release:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat "${GITHUB_EVENT_PATH}" | tee "${GITHUB_EVENT_NAME}".json
      - uses: eunchurn/action-publish@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: "main"
          USER_NAME: "${GITHUB_ACTOR}"
          USER_EMAIL: "${GITHUB_ACTOR}@users.noreply.github.com"
