name: Payload
on:
  push:
    branches: [ main ]
  release:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat "${GITHUB_EVENT_PATH}" | tee "${GITHUB_EVENT_NAME}".json
      - run: |
          git config --global user.name '${GITHUB_ACTOR}'
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git add -A && git commit -m "Adding file for event '${GITHUB_EVENT_NAME}'"
          git push -u origin main
